### ISSUE TITLE
Add compatibility with `react-native-maps` for android.

### ISSUE THREAD

**Issue by kirtanbodawala** [googlemaps/react-native-navigation-sdk#104]
Currently when using both the dependencies together we are getting `checkDebugDuplicateClasses error when having react-native-maps as dependency` error. We need to use `react-native-maps` to show static maps with custom marker using react-native-vector-icons` which is not supported by this sdk.

Below is the example of custom marker that we would like to implement with the dynamic text in the center:
<img width="43" alt="Screenshot 2024-04-12 at 3 50 21 PM" src="https://github.com/googlemaps/react-native-navigation-sdk/assets/20083520/7b5bb04a-45e7-43be-9d93-77b71e86de54">

Also their are other usecases that we are still not supported by this SDK. 

For more information refer to [Issue 76](https://github.com/googlemaps/react-native-navigation-sdk/issues/76)

**Comment by nexttrack07** [comment]
@jokerttu @illuminati1911 - Just wondering if these two libraries are compatible now with all the updates to the SDK now that we're on version 0.4.3? 
`react-native-maps` 
`https://github.com/bramus/react-native-maps-directions`

**Comment by jokerttu** [comment]
I've created a new feature issue (#254) that should address this issue by giving way to use classic map within this library.
This won't fix the issue where two libraries are not compatible with each other, but gives workaround to use classic map views. Please follow the new issue for updates, and we’ll close this once the new feature is implemented.
