### ISSUE TITLE
Hide Re-centre button.

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#146]
We would like so hide the Re-center button since it's not needed for our use case.
We just want to show some markers and user might not be there. so if they click the button it then navigates them away from our markers which is not what we want

**Comment by nexttrack07** [comment]
```
/**
   * Enables/disables the "Recenter" button on the map.
   *
   * @param isEnabled - Determines whether the button should be enabled or not.
   */
  setRecenterButtonEnabled(isEnabled: boolean): void;
  ```
  
This method is present in the `navigationViewController`. Maybe this is what you're looking for.
