### ISSUE TITLE
Location is not reported when simulating a location with simulator.simulateLocationsAlongExistingRoute

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#185]
I'm using simulator.simulateLocationsAlongExistingRoute() to simulate location for testing, but this doesn't seem to work. Only time location is updated is initially. But after simulation starts nothing new gets reported

https://github.com/googlemaps/react-native-driver-sdk/issues/11

**Comment by jokerttu** [comment]
This is driver issue as originally filed.
Let's continue discussion on the original issue at https://github.com/googlemaps/react-native-driver-sdk/issues/11
