### ISSUE TITLE
navigationViewController.setTrafficIncidentCardsEnabled not working

### ISSUE THREAD

**Issue by nexttrack07** [googlemaps/react-native-navigation-sdk#201]
`navigationViewController.setTrafficIncidentCardsEnabled(false)` still shows the dismiss dialog with traffic updates/changes. 

Environment: iOS and Android

This is in Simulator.

**Comment by jokerttu** [comment]
`setTrafficIncidentCardsEnabled` controls whether traffic incident cards should be shown when the user clicks on a traffic incident icon.

To control dialog visibility [`setTrafficPromptsEnabled`](https://developers.google.com/maps/documentation/navigation/android-sdk/reference/com/google/android/libraries/navigation/NavigationView#setTrafficPromptsEnabled(boolean)) should be used.

@nexttrack07 note that this method is not implemented; please file new issue to request this feature.

This is not bug on the `setTrafficIncidentCardsEnabled` method.
