### ISSUE TITLE
How to install the package???

### ISSUE THREAD

**Issue by tikotas** [googlemaps/react-native-navigation-sdk#228]
Hi there!

After trying to install your package, I was given an error which told me that your package could not be found.

#### Steps to reproduce

  1. npm i @googlemaps/react-native-navigation-sdk

#### Error

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@googlemaps%2freact-native-navigation-sdk - Not found
npm ERR! 404 
npm ERR! 404  '@googlemaps/react-native-navigation-sdk@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

### Screenshot

![Screenshot from 2024-08-18 01-50-27](https://github.com/user-attachments/assets/b2689c84-acd2-414e-b0d6-5c96841c55ba)

**Comment by jokerttu** [comment]
Hi @tikotas,

The package is currently in the release process and will be available on npm soon. That's why the README.md file already references the npm registry.

In the meantime, you can install the package directly from GitHub by using the following command:
```bash
npm install --save https://github.com/googlemaps/react-native-navigation-sdk#{version_tag}
```

**Comment by tikotas** [comment]
@jokerttu thanks for your support.

I'll try

**Comment by caio1985** [comment]
Hi @tikotas we have published it to NPM today: https://www.npmjs.com/package/@googlemaps/react-native-navigation-sdk

**Comment by tikotas** [comment]
@caio1985 thanks!
