### ISSUE TITLE
0.5.0 not working in Android

### ISSUE THREAD

**Issue by nexttrack07** [googlemaps/react-native-navigation-sdk#252]
Hello, 

This isn't a bug in the example app. The example app seems to work correctly. In our application, we had 0.4.3 and it was working correctly in both Android and iOS. However after upgrading to 0.5.0, Android seems to be broken even though iOS is working correctly. 

Here is the screenshot of the error that keeps coming up: 

![share_7898072896020320480](https://github.com/user-attachments/assets/9e3dd5d6-b98f-4003-88c6-3c7ef24eff5f)

This error shows up even if we remove the `mapViewCallbacks` prop from `NavigationView` component. It happens when opening any screen that has the NavigationView component.

**Comment by nexttrack07** [comment]
any help on how to debug this issue would be appreciated greatly!

**Comment by jokerttu** [comment]
@nexttrack07 thank you for reporting this to us.
I'll get back to you as soon as the issue is tracked down.
