### ISSUE TITLE
Adding Stop lights and stops on the Map 

### ISSUE THREAD

**Issue by akilakumarasamy** [googlemaps/react-native-navigation-sdk#261]
Our users are use to soficated maps currently with variours options available, in order for them to use our system we have provide few features that they are looking for like displaying "Stop"s and "Lights" on the map during navigation. Any plans of including these options on the map?
![image](https://github.com/user-attachments/assets/8e2b6948-1ec4-42bc-b812-9472c8b89b54)

**Comment by jokerttu** [comment]
Fixed with
https://github.com/googlemaps/react-native-navigation-sdk/pull/370
