### ISSUE TITLE
Failed to call into JavaScript module method NavJavascriptBridge.onLocationChanged(). Module exists, but the method is undefined.

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#272]
Started getting this error on 0.4.3.

```
Failed to call into JavaScript module method NavJavascriptBridge.onLocationChanged(). Module exists, but the method is undefined.
```

I wasn't yet able to reproduce this issue, so I can't give you more info yet. For now it seems to be an android only issue.

**Comment by ziga-hvalec** [comment]
Anything update?
We were able to reproduce this quite easily.
Steps to reproduce
- start navigation
- quit navigation
- quit app
- start app

Seem to me that stopping and starting navigation causes the above error.

sometimes this one also gets triggered
```
Failed to call into JavaScript module method NavJavascriptBridge.onRawLocationChanged(). Module exists, but the method is undefined.
```

**Comment by ArturoSalazarB16** [comment]
Hi @jokerttu @illuminati1911, can you please take a look?

**Comment by jokerttu** [comment]
@ziga-hvalec 

Hi, I was unable to reproduce this issue myself.

What methods are you calling when you "quit navigation"?

When `NavigationController.cleanup()` is called, the location listener is removed, and `onRawLocationChanged` and `onLocationChanged` events should no longer be triggered. Another way to stop these events from propagating is to call `NavigationController.stopUpdatingLocation()`.

Currently, the `NavJavascriptBridge` is only initialized after at least one listener is added or `init()` is called for navigation.

Does this happen only on Android?

To improve usability, I will create a PR to initialize the listeners during `NavigationProvider` initialization.

**Comment by jokerttu** [comment]
The issue could be related to this [documenentation mention](
https://developers.google.com/maps/documentation/navigation/android-sdk/reference/com/google/android/libraries/navigation/RoadSnappedLocationProvider#public-abstract-void-removelocationlistener-roadsnappedlocationprovider.locationlistener-listener):
> Since removal is not synchronous, in rare situations you may still get additional locations after deregistering.

I'll update the native implementation to be more state aware.

**Comment by ziga-hvalec** [comment]
@jokerttu 
Issue is Android only.

When quitting navigation i call this
```js
navigationController?.stopGuidance();
navigationController?.simulator.stopLocationSimulation();
navigationController?.clearDestinations();
```

when unmounting component i also call this
```js
  useEffect(() => {
    removeListeners(navigationCallbacks);
    addListeners(navigationCallbacks);
    return () => {
      removeListeners(navigationCallbacks);
    };
  }, [navigationCallbacks, addListeners, removeListeners]);
```

**Comment by ziga-hvalec** [comment]
@jokerttu I somehow managed to get this one too

```Invariant Violation: Failed to call into JavaScript module method NavJavascriptBridge.onRouteStatusResult(). Module exists, but the method is undefined., js engine: hermes
```

I hope the above PR also fixes this issue. What I did was start navigation and then restart app. then I got this error. But it doesn't always show up

**Comment by caio1985** [comment]
Is this still happening in the latest release?

**Comment by ziga-hvalec** [comment]
from our testing this seems to be fixed. But we'll need to do more testing to be sure

**Comment by ziga-hvalec** [comment]
This still happens for us on production. We'll try to reproduce it. But the flow where we were previously able to reproduce is fixed.
