### ISSUE TITLE
onRemainingTimeOrDistanceChanged not triggering.

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#273]
I've upgraded to v0.6.0 and i notice onRemainingTimeOrDistanceChanged no longer triggers. I tried android and ios.
I made no other changes to my code.

**Comment by ziga-hvalec** [comment]
Same also happens on 0.4.3

**Comment by illuminati1911** [comment]
@ziga-hvalec Thanks for reporting the issue. We'll investigate this.

**Comment by illuminati1911** [comment]
@ziga-hvalec We found the issue and are making a fix. The issue seems to only exist in the iOS code though. Can you test again with Android to see if the issue is there as well?

**Comment by ziga-hvalec** [comment]
Great. I'll check out android too and i'll let you know. Thats for a speedy response 👍

**Comment by ziga-hvalec** [comment]
I have tested android and it works as expected. Sorry for not mentioning this in the original post.

**Comment by jokerttu** [comment]
@ziga-hvalec fix is already landed to the main branch, and will be updated to npm as package version [v0.6.1](https://github.com/googlemaps/react-native-navigation-sdk/releases/tag/v0.6.1) as soon as release pipeline passes.

**Comment by ziga-hvalec** [comment]
Thanks. Tested and works now. Thanks
