### ISSUE TITLE
Example app documentation missing information about yarn install step

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#275]
Example app doesn't include the Navigation sdk dependency inside the package.json.

**Comment by jokerttu** [comment]
Hi @ziga-hvalec thank you for reporting this.

This seems to be documentation issue.
As example app uses yarn workspaces it has direct access to the navigation sdk package at the root folder.
Also see content in tsconfig.json file that maps @googlemaps/react-native-navigation-sdk directly to source files.
run `yarn install` in root folder and start the app with `yarn run example start` to start the metro on example folder.
