### ISSUE TITLE
When I am running the app on IOS simulator the app is running but the map is not visible it's only showing the white background

### ISSUE THREAD

**Issue by jaykishan23** [googlemaps/react-native-navigation-sdk#282]
<img width="322" alt="Screenshot 2024-09-30 at 12 07 42 PM" src="https://github.com/user-attachments/assets/243cad56-bcbb-479c-9921-8af30b1528aa">
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version
3. Library version and other environment information

#### Steps to reproduce

  1. ?

#### Code example

```
# example
```

#### Stack trace
```
# example
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jaykishan23** [comment]
Hi @caio1985 ,

yes everything is enabled in my I had also checked creating a demo maps project in that with the help of the same API_KEY I am also to render the map UI properly.

Can you please help me to resolve this

**Comment by caio1985** [comment]
Please provide us more details such as the output in the Metro console and any log output.

**Comment by jaykishan23** [comment]
The console is clear there is no error in the console

**Comment by jaykishan23** [comment]
I am getting below issue in IOS simulator please guide me to resolve this. @caio1985 @jokerttu 

<img width="329" alt="Screenshot 2024-09-30 at 8 18 57 PM" src="https://github.com/user-attachments/assets/3e0987a0-2ed2-4cd0-8bc6-72a1b3624939">

**Comment by jokerttu** [comment]
@jaykishan23 have you done following step in README.md file: [To set up, specify your API key in the application delegate ios/Runner/AppDelegate.m](https://github.com/googlemaps/react-native-navigation-sdk?tab=readme-ov-file#ios)

**Comment by ziga-hvalec** [comment]
Can this be an iphone 16/iOS 18 issue?

**Comment by nexttrack07** [comment]
did you add width and height in style tag? That was the issue for me 

`style={{ width: '100%', height: '100%' }}`

**Comment by jokerttu** [comment]
Hello @jaykishan23,

There have been some suggestions from the community regarding potential solutions. I'd like to check in and see if you're still encountering this issue. If you've resolved it, we are able to close this issue.
Could you alse share your solution? This will help us improve the package's documentation and implementation to avoid similar issues in the future.

**Comment by jaykishan23** [comment]
Hello @jokerttu ,
The issue is resolved after changing the api key and clearing cache .

Thanks for your support .
