### ISSUE TITLE
Navigation Event - Traffic updated  is triggering always in Android but not in iOS

### ISSUE THREAD

**Issue by akilakumarasamy** [googlemaps/react-native-navigation-sdk#287]
We are capturing navigation events and we see that "traffic updated" event is triggered always in Android, this is misleading and this is not happening in iOS. We are on [v0.6.0]. 

![image](https://github.com/user-attachments/assets/98ae5037-928b-4252-b56d-e2c34a4ab9d7)

**Comment by jokerttu** [comment]
@akilakumarasamy thanks for reporting this!
