### ISSUE TITLE
Map padding feature 

### ISSUE THREAD

**Issue by nexttrack07** [googlemaps/react-native-navigation-sdk#292]
This feature from the Maps SDK would be great for us: https://developers.google.com/maps/documentation/ios-sdk/configure-map#map_padding

 Currently we are able to increase and decrease the height of the map but the `navigationViewController.showRouteOverview` feature always spans the whole map. This makes it difficult to have overlays on the map because some of the route may be hidden as you can see in the screenshot below. 

<img width="320" alt="Screenshot 2024-10-07 at 3 51 39 PM" src="https://github.com/user-attachments/assets/5cb69733-cbd6-49f0-a9dd-6463a0439157">

**Comment by protolific** [comment]
+1, ideally I'd like this functionality to work similarly to [`fitBounds` from MapsJS](https://developers.google.com/maps/documentation/javascript/reference/map#Map.fitBounds)
