### ISSUE TITLE
While installing this library in react native latest version "0.75.4" it's showing below errors of Duplicate class

### ISSUE THREAD

**Issue by jaykishan23** [googlemaps/react-native-navigation-sdk#295]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version
3. Library version and other environment information

#### Steps to reproduce

  1. ?

#### Code example

```
# example
```

#### Stack trace
```
# example
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jaykishan23** [comment]
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable > Duplicate class com.google.android.gms.maps.CameraUpdate found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.CameraUpdateFactory found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.GoogleMap found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.GoogleMap$CancelableCallback found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.GoogleMap$InfoWindowAdapter found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraChangeListener found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraIdleListener found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraMoveCanceledListener found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraMoveListener found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0) Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraMoveStartedListener found in modules navigation-5.3.1.aar -> navigation-5.3.1-runtime (com.google.android.libraries.navigation:navigation:5.3.1) and play-services-maps-18.2.0.aar -> play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)

**Comment by jokerttu** [comment]
Hi @jaykishan23,

Are you using another package that also depends on Google Maps? The Navigation SDK includes the Google Maps package, which can cause conflicts with other packages using Google Maps services.

Please note that this package can also be used to display a classic Google Maps view, so using another package at the same time should not be necessary. If there are any features missing from this package's classic map view that you need, please submit a feature request.

Let us know if this is the case, and we can close the issue.

**Comment by jaykishan23** [comment]
Actually I was using google maps package but not I had uninstalled it.
Now the app is running but when we click on navigation button to go on the navigation screen the app is crashing and nothing is showing in console.
please guide @jokerttu

**Comment by jokerttu** [comment]
@jaykishan23
Make sure you have followed all the README.md steps.
You can run the app on Android Studio / XCode to get more error logs.

Closing this issue. Please open new issue for new issues not related to this, and fill up the issue template so we can get proper data of the issue.
