### ISSUE TITLE
I had tried to install this library In react native latest version "0.75.4" but we are unable to install pod for ios it's showing below errors

### ISSUE THREAD

**Issue by jaykishan23** [googlemaps/react-native-navigation-sdk#298]
!] CocoaPods could not find compatible versions for pod "react-native-navigation-sdk":
  In Podfile:
    react-native-navigation-sdk (from `../node_modules/@googlemaps/react-native-navigation-sdk`)

Specs satisfying the `react-native-navigation-sdk (from `../node_modules/@googlemaps/react-native-navigation-sdk`)` dependency were found, but they required a higher minimum deployment target.

**Comment by jokerttu** [comment]
Please update your iOS deployment target of your project to match the one in the README.md and here https://github.com/googlemaps/react-native-navigation-sdk/blob/main/react-native-navigation-sdk.podspec#L30
