### ISSUE TITLE
Showing white screen when implementing version 0.6.1.

### ISSUE THREAD

**Issue by hemantrajputcdn** [googlemaps/react-native-navigation-sdk#318]
![Screenshot 2024-10-25 at 7 07 19 PM](https://github.com/user-attachments/assets/9260292e-1667-4762-9885-ff3512d5f4be)
OS:- Android
version:- 14.0

I think the issue is google map is not initializing.

**Comment by jokerttu** [comment]
Hi @hemantrajputcdn

Could you please provide more details about your local setup? Specifically:

- React version
- React Native version
- Android OS version (you mentioned Android 14.0, but any specific device/emulator model?)
- Share relevant Logcat logs from Android Studio, especially any errors or warnings that appear when initializing the map.
- Confirm if Google Play Services are up-to-date on the device/emulator.
- Let us know if you've tried cleaning and rebuilding the project.

This information will help us narrow down what might be causing the white screen. Thank you!

**Comment by hemantrajputcdn** [comment]
Than you for your response. I've resolved it.

**Comment by xiaobc1234** [comment]
> Than you for your response. I've resolved it.
@hemantrajputcdn   May I ask how you solved it? I also encountered this problem.

**Comment by hemantrajputcdn** [comment]
I just followed the example folder structure and added all the necessary code from there.
