### ISSUE TITLE
Incompatibility  Java version for switch expressions

### ISSUE THREAD

**Issue by Aruna1401** [googlemaps/react-native-navigation-sdk#328]
Hi team,

I'm experiencing the below issue even I'm using java 17 for my react native project.Can anyone help me out for this?

\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\EnumTranslationUtil.java:47: error: switch expressions are not supported in -source 11
    return switch (jsValue) {
           ^
  (use -source 14 or higher to enable switch expressions)
node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\EnumTranslationUtil.java:48: error: switch rules are not supported in -source 11
      case 0 -> Navigator.TaskRemovedBehavior.CONTINUE_SERVICE;
             ^
  (use -source 14 or higher to enable switch rules)

**Comment by jokerttu** [comment]
@Aruna1401
Thanks for reporting this issue

**Comment by jokerttu** [comment]
@Aruna1401 
Could you please run `npx react-native doctor` and give use the output.

**Comment by Aruna1401** [comment]
Hi @jokerttu ,
Even im tried install Android 33 API but still it is coming like below.
✓ JDK - Required to compile Java code
✓ Android Studio - Required for building and installing your app on Android
✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 33.0.0
✓ ANDROID_HOME - Environment variable that points to your Android SDK installation

**Comment by Aruna1401** [comment]
Hi @jokerttu 
Can u pls help me out with this?
Thanks in Advance

**Comment by Aruna1401** [comment]
Hi @jokerttu 
    "react": "18.3.1",
    "react-native": "0.76.1"
    
    Android
✓ Adb - Required to verify if the android device is attached correctly
✓ JDK - Required to compile Java code
✖ Android SDK - Required for building and installing your app on Android

   - Versions found: N/A

   - Version supported: 35.0.0
 
Now that issue has been resolved . We are experiencing the below issue now.Could you pls assist on this ?
No modules to process in combine-js-to-schema-cli. If this is unexpected, please check if you set up your NativeComponent correctly. See combine-js-to-schema.js for how codegen finds modules.
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\MapViewFragment.java:60: error: cannot access Fragment
public class MapViewFragment extends SupportMapFragment
       ^
  class file for android.support.v4.app.Fragment not found
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\MapViewFragment.java:84: error: method does not override or implement a method from a supertype
  @Override
  ^
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\MapViewFragment.java:86: error: cannot find symbol
    super.onViewCreated(view, savedInstanceState);
         ^
  symbol: method onViewCreated(View,Bundle)
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\MapViewFragment.java:94: error: cannot find symbol
            mMapViewController.initialize(googleMap, () -> requireActivity());
                                                           ^
  symbol: method requireActivity()
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\MapViewFragment.java:561: error: cannot find symbol
      if (ActivityCompat.checkSelfPermission(getActivity(), permission.ACCESS_FINE_LOCATION)
                                             ^
  symbol:   method getActivity()
  location: class MapViewFragment
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\MapViewFragment.java:563: error: cannot find symbol
&& ActivityCompat.checkSelfPermission(getActivity(), permission.ACCESS_COARSE_LOCATION)
                                                ^
  symbol:   method getActivity()
  location: class MapViewFragment
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\NavViewManager.java:345: error: incompatible types: MapViewFragment cannot be converted to Fragment
        fragment = mapFragment;
                   ^
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\NavViewManager.java:353: error: incompatible types: NavViewFragment cannot be converted to Fragment
        fragment = navFragment;
                   ^
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\NavViewFragment.java:43: error: NavViewFragment is not abstract and does not override abstract method getView() in IMapViewFragment
public class NavViewFragment extends SupportNavigationFragment
       ^
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\NavViewFragment.java:69: error: method does not override or implement a method from a supertype
  @Override
  ^
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\NavViewFragment.java:71: error: cannot find symbol
    super.onViewCreated(view, savedInstanceState);
         ^
  symbol: method onViewCreated(View,Bundle)
D:\React native\googleNavigationSDK\node_modules\@googlemaps\react-native-navigation-sdk\android\src\main\java\com\google\android\react\navsdk\NavViewFragment.java:81: error: cannot find symbol
            mMapViewController.initialize(googleMap, () -> requireActivity());
                                                           ^
  symbol: method requireActivity()
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
12 errors

**Comment by jokerttu** [comment]
@Aruna1401 
I can reproduce this issue with given react and react-native versions.
Please use older react native version 0.74.1 for now if possible:
`npx @react-native-community/cli@latest init NewProjectName --version 0.74.1 `

We will work on supporting the new react native architecture introduced in version 0.76

**Comment by jokerttu** [comment]
Closing this as a favor of https://github.com/googlemaps/react-native-navigation-sdk/issues/331

**Comment by Aruna1401** [comment]
I'll check and confirm
