### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method ifPresentOrElse

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#335]
This started happening on 0.8.0. It happens when users navigate to the screen where we have the navigation. 
We have very limited release right now so we don't yet have a lot of data.
Happens every time. This happened until now only Galaxy Note10+ with android 12.

java.lang.NoSuchMethodError: No virtual method ifPresentOrElse(Ljava/util/function/Consumer;Ljava/lang/Runnable;)V in class Ljava/util/Optional; or its super classes (declaration of 'java.util.Optional' appears in /apex/com.android.art/javalib/core-oj.jar)
    at com.google.android.gms.internal.auth.zzcc$$ExternalSyntheticApiModelOutline0.m
    at com.google.android.libraries.navigation.internal.dx.v.run(PG:7)
    at com.google.android.libraries.geo.mapcore.renderer.at.b(PG:56)
    at com.google.android.libraries.navigation.internal.py.ad.e(PG:23)
    at com.google.android.libraries.geo.mapcore.renderer.bj.run(PG:60)

**Comment by ziga-hvalec** [comment]
we were able to reproduce this on another device with android 12.

**Comment by ziga-hvalec** [comment]
I figured out that as soon as i call navigationController.init() app crashes. Map without navigation works correctly.

**Comment by jokerttu** [comment]
@illuminati1911 can you check this?

**Comment by illuminati1911** [comment]
Hey @ziga-hvalec, which JDK version are you using?

**Comment by ziga-hvalec** [comment]
We use JDK 17.

**Comment by jokerttu** [comment]
@ziga-hvalec, we haven't been able to reproduce this exact issue yet. Could you provide more details on your build.gradle file configuration, specifically:

compileOptions
minSdkVersion
targetSdkVersion
compileSdkVersion

This issue is most likely related to Java compatibility and may require the use of desugaring libraries. Please refer to the release notes for Android SDK version 6.0.0 at: https://developers.google.com/maps/documentation/navigation/android-sdk/release-notes#September_13_2024

> An issue related to the use of earlier versions of desugaring libraries may cause some apps that implement the Navigation SDK to crash with the following NoSuchMethod error at runtime:
> No virtual method toSeconds()J in class Ljava/time/Duration; or its super classes (declaration of 'java.time.Duration' appears in ...)
> If you experience this issue, update your app to use com.android.tools:desugar_jdk_libs_nio:2.0.3 for desugaring. You may also need to upgrade to Gradle 8.4 and the Android Gradle plugin version 8.3.0. For more information, see [Set up your Android Studio project](https://developers.google.com/maps/documentation/navigation/android-sdk/android-studio-setup#update_the_gradle_build_script) or the [Navigation SDK sample app](https://github.com/googlemaps-samples/android-navigation-samples/blob/main/navigation-sample/app/build.gradle) on GitHub.

**Comment by xiaobc1234** [comment]
Is this problem solved? I am using desugaring libraries locally and it still crashes on Java 17. My phone is running Android 10.The error message is as follows:

` FATAL EXCEPTION: GL-Map
                                                                                        Process: com.sampleapp, PID: 30434
                                                                                        java.lang.NoSuchMethodError: No virtual method ifPresentOrElse(Ljava/util/function/Consumer;Ljava/lang/Runnable;)V in class Ljava/util/Optional; or its super classes (declaration of 'java.util.Optional' appears in /apex/com.android.runtime/javalib/core-oj.jar)
                                                                                        	at com.google.android.libraries.navigation.internal.dx.v.run(PG:7)
                                                                                        	at com.google.android.libraries.geo.mapcore.renderer.at.b(PG:56)
                                                                                        	at com.google.android.libraries.navigation.internal.py.ad.e(PG:23)
                                                                                        	at com.google.android.libraries.geo.mapcore.renderer.bj.run(PG:60)`

**Comment by ziga-hvalec** [comment]
I follow instruction from the PR but still doesn't work.
I have disabled new architecture
enabled jetifier
updated gradle to 8.4 and 8.3.0
added Desugaring

app still crashes as soon as navigation is initialized

**Comment by jokerttu** [comment]
@ziga-hvalec 

Please provide the error output from logcat.

You can also test if this issue is visible in example app on branch:
`chore/update-react-native-version-to-0.76.2-for-example-app`
See PR: https://github.com/googlemaps/react-native-navigation-sdk/pull/340

**Comment by ziga-hvalec** [comment]
I managed to get it working with java 23. Ii need to check lower versions now. Please add which java version we need to use. Just following the instruction did not work.

**Comment by ziga-hvalec** [comment]
I cleared cache and now it works even with java 17. Sorry
So anyone that follows instructions but doesn't clear cache will still get the crash.
