### ISSUE TITLE
Destination title not appearing in navigation banner

### ISSUE THREAD

**Issue by jmcguiresignifyhealth** [googlemaps/react-native-navigation-sdk#354]
#### Summary

While using the navigation-sdk, our team noticed that the title of the destination in the navigation banner was not the title that we set.  Specifically, the title was "Destination" instead of an address. 

#### Environment details

OS: Android
Version: 15
Library Version: 0.8.1

#### Steps to reproduce

1. In the code, create a waypoint with a title
2. Set that waypoint as the destination
3. Navigate to that destination 

#### Code example

```
    const waypoint: Waypoint = {
      title: 'Town hall',
      position: {
        lat: Number(latitude),
        lng: Number(longitude),
      },
    };

    const routingOptions: RoutingOptions = {
      travelMode: TravelMode.DRIVING,
      avoidFerries: true,
      avoidTolls: false,
    };

    navigationController.setDestination(waypoint, routingOptions,);
```

![image](https://github.com/user-attachments/assets/9f36ba44-b06f-4b45-9422-581049864db5)

**Comment by akilakumarasamy** [comment]
Hi, This is blocing the users to see the real address and has complaints from users. Can we get this fixed?

**Comment by caio1985** [comment]
@jokerttu Can you please take a look?

**Comment by jokerttu** [comment]
Hi,
I was able to reproduce this issue.
The title is correctly assigned to the SDK in the Waypoint object but is not displayed on the navigation header, as per the behavior described in the native SDK documentation.

This title is intended to appear in the notification tray, not in the destination header. Please refer to the documentation for clarification:
https://developers.google.com/maps/documentation/navigation/android-sdk/reference/com/google/android/libraries/navigation/Waypoint#public-string-gettitle

Create feature request for Navigation SDK for Android at: https://issuetracker.google.com/issues?q=componentid:1657535

**Comment by ArturoSalazarB16** [comment]
Hi @jmcguiresignifyhealth @akilakumarasamy  - can you please try removing the `title` from the waypoint object and see if this helps?

**Comment by jokerttu** [comment]
As a workaround it is also possible to create custom instructions by hiding the header and creating custom overlay using the turn-by-turn event information.

**Comment by jmcguiresignifyhealth** [comment]
@ArturoSalazarB16 @jokerttu 

Thank you both.  It's good to know we can create a custom header too.  In case the need arises.

I went ahead and tried Arturo's suggestion and removed title from the waypoint.  That solved the issue.  After doing that, I now see address line 1 in the top navigation banner instead of "Destination". Gonna go ahead and close this ticket. Thanks again.
