### ISSUE TITLE
Zooming the camera in navigation mode.

### ISSUE THREAD

**Issue by tikotas** [googlemaps/react-native-navigation-sdk#365]
It would be nice if there was an option to increase the camera zoom in navigation mode. 
Sometimes you need the maximum zoom in walking mode, but you have to manually increase the zoom to achieve the desired result.

**Comment by jokerttu** [comment]
Note that this package is only wrapper for underlaying Navigation SDK implementation for Android and iOS.
As this feature is not available on these SDK's, currently devs need to set the zoom level programmically right after navigation mode is enabled.
To open feature request for Navigation SDK's file new feature request to https://issuetracker.google.com/issues/new
