### ISSUE TITLE
Custom Marker: Not able to add image for 'Custom Marker'

### ISSUE THREAD

**Issue by MallikarjunH09** [googlemaps/react-native-navigation-sdk#385]
Hello,
I am trying to add custom marker which contains image as well

-  OS type and version : Mac OS, iOS device.
-  Library version and other environment information: "@googlemaps/react-native-navigation-sdk": "^0.9.1",

Here is the code I tried,

```
const addMarker = async (imgPath?: string) => {
        if (mapViewController) {
            const cameraPosition = await mapViewController.getCameraPosition();

            const marker: Marker = await mapViewController.addMarker({
                position: cameraPosition.target,
                visible: true,
                title: 'Custom Marker',
                snippet: 'This is a marker with custom image and text',
                alpha: 1.0,
                rotation: 0,
                flat: false,
                draggable: true,
                imgPath: imgPath,
            });
        }
    };

    const addCustomMarker = async () => {
       // let imagePath = Image.resolveAssetSource(require('assets/map-icons/map-position-icon.png')).uri;
        // let imagePath = './assets/map-icons/map-position-icon.png';
        const imagePath = require('assets/map-icons/map-position-icon.png');
        await addMarker(imagePath);
    };
```

I don't no, why my custom image is not showing as marker, it is showing default marker icon only. 
What is the correct way to show image as marker?

**Comment by MallikarjunH09** [comment]
Resolved the issue.
In this case i.e for imgPath, images should added in native Android/iOS folder's assets path.
By doing this change, issue got resolved.

**Comment by raffiot** [comment]
Hey @MallikarjunH09 ! Thanks for posting your issue, can you give the exact path where you added the image in iOS and Android?
For iOS I added the image in /MyApp/Images.xcassets/my_image.png but it does not seem to work with
```
const marker = await mapViewController?.addMarker({
      position: destination.position,
      visible: true,
      imgPath: "my_image.png",
    });
```
Thanks! 🙏

**Comment by raffiot** [comment]
Thanks for your answer @MallikarjunH09, my question is in which folder did you store the image? I have
iOS: ios/MyApp/Images.xcassets/<image>.png
Android: android/app/src/main/res/drawable/<image>.png
But it does not work with iOS. Can you share with my the path that you used in iOS?

**Comment by MallikarjunH09** [comment]
For the iOS:   ios/MyApp/Images.xcassets/arrow.png
For the Android: android/app/src/main/assets/arrow.png

And here is the code sample,

const marker: Marker = await mapViewController.addMarker({
              position: { lat: latlng.lat, lng: latlng.lng },
              visible: true,
              alpha: 0.8,
              rotation: 0,
              flat: false,
              draggable: true,
              title: "Some title",
              snippet: "",
              imgPath: "arrow.png",
            })

Which is working fine in both iOS and Android apps.

**Comment by raffiot** [comment]
Ok thanks a lot it's another problem on my side then, I'll have a look! 🙏
