### ISSUE TITLE
are termsAndConditionsDialogOptions and onNavigationViewControllerCreated mandatory if we only want to show a simple map without navigation?

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#39]
Like title says, we would like to only show a simple map without navigation. Are onNavigationViewControllerCreated and termsAndConditionsDialogOptions in this case still mandatory?

**Comment by jokerttu** [comment]
@ziga-hvalec the behaviour was changed and landed with #199 
You do not need to use termsAndConditionsDialogOptions anymore to initialize map view.
