### ISSUE TITLE
App freezing while navigating

### ISSUE THREAD

**Issue by anielgroup** [googlemaps/react-native-navigation-sdk#87]
When the navigation works for a long time and the trip is longer than 15 minutes, the phone starts to heat up very much and freezes appear. When the screen just freezes and then prompts you to close the application

**Comment by aim-leo** [comment]
Hello, I think I have encountered the same app stuck problem as you, and I have no way to solve it.
My program needs to get the time and distance of each waypoint. In the Android SDK, it should call the getTimeAndDistanceList method. Currently, this method is not implemented in the @googlemaps/react-native-navigation-sdk library, so I added the following code to NavModule.java:
```
public void getTimeAndDistanceList(final Promise promise) {
    if (mNavigator == null) {
        promise.reject(JsErrors.NO_NAVIGATOR_ERROR_CODE, JsErrors.NO_NAVIGATOR_ERROR_MESSAGE);
        return;
    }

    List<TimeAndDistance> timeAndDistanceList = mNavigator.getTimeAndDistanceList();
    WritableArray array = Arguments.createArray();
    if (timeAndDistanceList != null && !timeAndDistanceList.isEmpty()) {
        for (TimeAndDistance timeAndDistance : timeAndDistanceList) {
            WritableMap map = Arguments.createMap();
            map.putInt("delaySeverity", timeAndDistance.getDelaySeverity());
            map.putInt("meters", timeAndDistance.getMeters());
            map.putInt("seconds", timeAndDistance.getSeconds());
            array.pushMap(map);
        }
    }
    promise.resolve(array);
  }
```
Most of the time it works fine, but when I call this function every 0.1s, usually within a few minutes the whole screen freezes and I don't see any errors in the Android Studio logs. If I do nothing, it stays like this and when I try to tap the screen the app crashes and exits.
I'd love to know if this is a problem with the Google Map SDK itself or my implementation, and I'd be grateful for any information you can provide.
